.PHONY: clean All

All:
	@echo "----------Building project:[ JennicksMineSweeper - Debug ]----------"
	@cd "JennicksMineSweeper" && "$(MAKE)" -f  "JennicksMineSweeper.mk"
clean:
	@echo "----------Cleaning project:[ JennicksMineSweeper - Debug ]----------"
	@cd "JennicksMineSweeper" && "$(MAKE)" -f  "JennicksMineSweeper.mk" clean
